stages:
  - dev
  - prod

deploy_dev:
  image: node:alpine
  stage: dev
  environment:
    name: dev
    url: https://dev-endernet-io.firebaseapp.com
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --only hosting:dev -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

deploy_prod:
  image: node:alpine
  stage: prod
  environment:
    name: prod
    url: https://endernet-io.firebaseapp.com
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --only hosting:prod -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN